### PR TITLE
Make small edits to README

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
- Removed forced line breaks in favour of letting the text editor handle breaks based on the user's preferences
- Cleaned some typos and style
- Added links where relevant

### CODE REVIEW

**Comment by betatim** [comment]
I like the edits, but the inner 80characters per line junkie is still coming to terms with the "every paragraph on a line" changes. It does make it easier to get good diffs. What do you think about one sentence per line (which is super duper for diffs)?

**Comment by betatim** [comment]
On #SOS<place> do you think it adds something? I don't think you can [search](https://twitter.com/search?q=%23moz*&src=typd) for partial hashtags (#moz\* in this case). In addition place names are kind of ambiguous.

So overall I would be -0 on this change. Makes the rule more complex and not so much benefit.

**Comment by RaoOfPhysics** [comment]
> I like the edits, but the inner 80characters per line junkie is still coming to terms with the "every paragraph on a line" changes. It does make it easier to get good diffs. What do you think about one sentence per line (which is super duper for diffs)?

I'm a HUGE fan of new sentences on new lines. Will fix this.

> On #SOS do you think it adds something? I don't think you can search for partial hashtags (#moz\* in this case). In addition place names are kind of ambiguous.

I suggested #SOS and #SOSlocation because otherwise you'll have too much noise on just #SOS that might not be relevant to all locations. I'm not suggesting using one or the other. Place names will be chosen organically as they tend to be chosen with any hashtags. People will converge. :) If you still think I should remove it, I will do so. Let me know!

**Comment by betatim** [comment]
> I'm a HUGE fan of new sentences on new lines. Will fix this.

🎉 🎈

**Comment by betatim** [comment]
For some baseline: [#SOS receives a tweet a minute](https://twitter.com/search?f=tweets&vertical=default&q=%23sos&src=typd) or so right now.

In an ideal world everyone geotags -> no need to split hashtags by location. You can ask the websearch to only show you tweets from "around X" (via the API it is super simple to make a bounding box)

How far are we from that ideal world? How high is the background going to be?

Maybe for now we store it in the optional/nice to have guidelines? Or add it to the geotagging one as "if you can't geotag then do #SOS<location>"?

**Comment by RaoOfPhysics** [comment]
You're probably right -- a combination of #SOS and geotagging should suffice. Let's revisit this if more people feel differently, but for now I'll remove the #SOSlocation suggestion.

**Comment by betatim** [comment]
:shipit:

**Pull request merged**
